In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/04-11-2021.csv")
df.head()

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,ISO3,Testing_Rate,Hospitalization_Rate
0,Alabama,US,2021-04-12 04:30:34,32.3182,-86.9023,518899,10712,NaN,NaN,1.0,10582.896627,2436418.0,NaN,2.064371,84000001.0,USA,49690.517490,NaN
1,Alaska,US,2021-04-12 04:30:34,61.3707,-152.4044,64782,313,NaN,NaN,2.0,8855.504446,1966048.0,NaN,0.483159,84000002.0,USA,268752.845006,NaN
2,American Samoa,US,2021-04-12 04:30:34,-14.2710,-170.1320,0,0,NaN,NaN,60.0,0.000000,2140.0,NaN,NaN,16.0,ASM,3846.084722,NaN
3,Arizona,US,2021-04-12 04:30:34,33.7298,-111.4312,849561,17086,NaN,NaN,4.0,11671.850959,8761941.0,NaN,2.011156,84000004.0,USA,120377.547307,NaN
4,Arkansas,US,2021-04-12 04:30:34,34.9697,-92.3731,332153,5661,NaN,NaN,5.0,11006.447072,2898574.0,NaN,1.704335,84000005.0,USA,96049.113859,NaN

In [2]:
print(df)

              Province_State Country_Region          Last_Update      Lat  \
0                    Alabama             US  2021-04-12 04:30:34  32.3182
1                     Alaska             US  2021-04-12 04:30:34  61.3707
2             American Samoa             US  2021-04-12 04:30:34 -14.2710
3                    Arizona             US  2021-04-12 04:30:34  33.7298
4                   Arkansas             US  2021-04-12 04:30:34  34.9697
5                 California             US  2021-04-12 07:30:55  36.1162
6                   Colorado             US  2021-04-12 04:30:34  39.0598
7                Connecticut             US  2021-04-12 04:30:34  41.5978
8                   Delaware             US  2021-04-12 04:30:34  39.3185
9           Diamond Princess             US  2021-04-12 04:30:34      NaN
10      District of Columbia             US  2021-04-12 04:30:34  38.8974
11                   Florida             US  2021-04-12 04:30:34  27.7663
12                   Georgia             US  2021-04-12 04:30:34  33.0406
13            Grand Princess             US  2021-04-12 04:30:34      NaN
14                      Guam             US  2021-04-12 04:30:34  13.4443
15                    Hawaii             US  2021-04-12 04:30:34  21.0943
16                     Idaho             US  2021-04-12 04:30:34  44.2405
17                  Illinois             US  2021-04-12 04:30:34  40.3495
18                   Indiana             US  2021-04-12 04:30:34  39.8494
19                      Iowa             US  2021-04-12 04:30:34  42.0115
20                    Kansas             US  2021-04-12 04:30:34  38.5266
21                  Kentucky             US  2021-04-12 04:30:34  37.6681
22                 Louisiana             US  2021-04-12 04:30:34  31.1695
23                     Maine             US  2021-04-12 04:30:34  44.6939
24                  Maryland             US  2021-04-12 04:30:34  39.0639
25             Massachusetts             US  2021-04-12 04:30:34  42.2302
26                  Michigan             US  2021-04-12 04:30:34  43.3266
27                 Minnesota             US  2021-04-12 04:30:34  45.6945
28               Mississippi             US  2021-04-12 04:30:34  32.7416
29                  Missouri             US  2021-04-12 04:30:34  38.4561
30                   Montana             US  2021-04-12 04:30:34  46.9219
31                  Nebraska             US  2021-04-12 04:30:34  41.1254
32                    Nevada             US  2021-04-12 04:30:34  38.3135
33             New Hampshire             US  2021-04-12 04:30:34  43.4525
34                New Jersey             US  2021-04-12 04:30:34  40.2989
35                New Mexico             US  2021-04-12 04:30:34  34.8405
36                  New York             US  2021-04-12 04:30:34  42.1657
37            North Carolina             US  2021-04-12 04:30:34  35.6301
38              North Dakota             US  2021-04-12 04:30:34  47.5289
39  Northern Mariana Islands             US  2021-04-12 04:30:34  15.0979
40                      Ohio             US  2021-04-12 04:30:34  40.3888
41                  Oklahoma             US  2021-04-12 04:30:34  35.5653
42                    Oregon             US  2021-04-12 04:30:34  44.5720
43              Pennsylvania             US  2021-04-12 04:30:34  40.5908
44               Puerto Rico             US  2021-04-12 04:30:34  18.2208
45              Rhode Island             US  2021-04-12 04:30:34  41.6809
46            South Carolina             US  2021-04-12 04:30:34  33.8569
47              South Dakota             US  2021-04-12 04:30:34  44.2998
48                 Tennessee             US  2021-04-12 04:30:34  35.7478
49                     Texas             US  2021-04-12 04:30:34  31.0545
50                      Utah             US  2021-04-12 04:30:34  40.1500
51                   Vermont             US  2021-04-12 04:30:34  44.0459
52            Virgin Islands             US  2021-04-12 04:30:34  18.3358
53                  Virginia             US  2021-04-12 04:30:34  37.7693
54                Washington             US  2021-04-12 04:30:34  47.4009
55             West Virginia             US  2021-04-12 04:30:34  38.4912
56                 Wisconsin             US  2021-04-12 04:30:34  44.2685
57                   Wyoming             US  2021-04-12 04:30:34  42.7560

       Long_  Confirmed  Deaths  Recovered  Active     FIPS  Incident_Rate  \
0   -86.9023     518899   10712        NaN     NaN      1.0   10582.896627
1  -152.4044      64782     313        NaN     NaN      2.0    8855.504446
2  -170.1320          0       0        NaN     NaN     60.0       0.000000
3  -111.4312     849561   17086        NaN     NaN      4.0   11671.850959
4   -92.3731     332153    5661        NaN     NaN      5.0   11006.447072
5  -119.6816    3700471   60452        NaN     NaN      6.0    9365.382960
6  -105.3111     478678    6157        NaN     NaN      8.0    8312.206012
7   -72.7554     321586    7944        NaN     NaN      9.0    9019.919014
8   -75.5071      98570    1578        NaN     NaN     10.0   10122.575901
9        NaN         49       0        NaN     NaN  88888.0            NaN
10  -77.0268      45830    1081        NaN     NaN     11.0    6493.810122
11  -81.6868    2124233   34021        NaN     NaN     12.0    9890.394877
12  -83.6431    1073792   19488        NaN     NaN     13.0   10113.489874
13       NaN        103       3        NaN     NaN  99999.0            NaN
14  144.7937       7833     136        NaN     NaN     66.0    4769.559578
15 -157.4983      32067     471        NaN     NaN     15.0    2264.823374
16 -114.4788     183153    1993        NaN     NaN     16.0   10248.815796
17  -88.9861    1279663   23793        NaN     NaN     17.0   10098.493342
18  -86.2583     698692   13148        NaN     NaN     18.0   10378.331424
19  -93.2105     357019    5857        NaN     NaN     19.0   11315.723581
20  -96.7265     305773    4933        NaN     NaN     20.0   10495.710383
21  -84.6701     433085    6250        NaN     NaN     21.0    9693.748849
22  -91.8678     448838   10216        NaN     NaN     22.0    9654.934161
23  -69.3819      53960     750        NaN     NaN     23.0    4014.247753
24  -76.8021     426730    8455        NaN     NaN     24.0    7058.428498
25  -71.5301     659569   17387        NaN     NaN     25.0    9569.368341
26  -84.5361     820404   17563        NaN     NaN     26.0    8214.836760
27  -93.9002     542053    7035        NaN     NaN     27.0    9611.495927
28  -89.6787     307449    7096        NaN     NaN     28.0   10330.430365
29  -92.2884     588626    8885        NaN     NaN     29.0    9590.760169
30 -110.4544     106183    1523        NaN     NaN     30.0    9934.991177
31  -98.2681     214207    2220        NaN     NaN     31.0   11073.517066
32 -117.0554     308024    5332        NaN     NaN     32.0   10000.272713
33  -71.5639      88854    1257        NaN     NaN     33.0    6534.770992
34  -74.5210     953490   24870        NaN     NaN     34.0   10734.852553
35 -106.2485     193368    3976        NaN     NaN     35.0    9221.925107
36  -74.9481    1956594   51117        NaN     NaN     36.0   10057.767830
37  -79.8064     929406   12248        NaN     NaN     37.0    8861.542299
38  -99.7840     104745    1502        NaN     NaN     38.0   13744.944637
39  145.6739        160       2        NaN     NaN     69.0     290.149427
40  -82.7649    1039455   19200        NaN     NaN     39.0    8892.515249
41  -96.9289     442805    6669        NaN     NaN     40.0   11190.504050
42 -122.0709     170568    2440        NaN     NaN     41.0    4044.064388
43  -77.2098    1073924   25393        NaN     NaN     42.0    8388.727720
44  -66.5901     115299    2155        NaN     NaN     72.0    3610.208116
45  -71.5118     141097    2638        NaN     NaN     44.0   13319.066871
46  -80.9450     562691    9276        NaN     NaN     45.0   10928.767844
47  -99.4388     119705    1946        NaN     NaN     46.0   13531.202418
48  -86.6923     822085   12001        NaN     NaN     47.0   12037.839422
49  -97.5635    2826977   49212        NaN     NaN     48.0    9749.581328
50 -111.8624     390104    2159        NaN     NaN     49.0   12168.094529
51  -72.7107      21202     231        NaN     NaN     50.0    3397.816308
52  -64.8963       2971      26        NaN     NaN     78.0    2769.698326
53  -78.1700     635552   10472        NaN     NaN     51.0    7445.967843
54 -121.4905     376230    5322        NaN     NaN     53.0    4940.712890
55  -80.9545     146169    2745        NaN     NaN     54.0    8156.083178
56  -89.6165     645514    7380        NaN     NaN     55.0   11086.669252
57 -107.3025      56873     701        NaN     NaN     56.0    9826.715438

    Total_Test_Results  People_Hospitalized  Case_Fatality_Ratio         UID  \
0            2436418.0                  NaN             2.064371  84000001.0
1            1966048.0                  NaN             0.483159  84000002.0
2               2140.0                  NaN                  NaN        16.0
3            8761941.0                  NaN             2.011156  84000004.0
4            2898574.0                  NaN             1.704335  84000005.0
5           56078860.0                  NaN             1.633630  84000006.0
6            7269129.0                  NaN             1.286251  84000008.0
7            7476439.0                  NaN             2.470257  84000009.0
8            1620589.0                  NaN             1.600893  84000010.0
9                  NaN                  NaN             0.000000  84088888.0
10           1423475.0                  NaN             2.358717  84000011.0
11          21476893.0                  NaN             1.601566  84000012.0
12           7975847.0                  NaN             1.814877  84000013.0
13                 NaN                  NaN             2.912621  84099999.0
14            134339.0                  NaN             1.736244       316.0
15           1328203.0                  NaN             1.468800  84000015.0
16            685952.0                  NaN             1.088161  84000016.0
17          21102407.0                  NaN             1.859318  84000017.0
18           9187249.0                  NaN             1.881802  84000018.0
19           1393075.0                  NaN             1.640529  84000019.0
20           1335069.0                  NaN             1.600861  84000020.0
21           4393731.0                  NaN             1.443135  84000021.0
22           6186986.0                  NaN             2.276100  84000022.0
23           1872183.0                  NaN             1.389918  84000023.0
24           9090254.0                  NaN             1.981347  84000024.0
25          19748011.0                  NaN             2.636115  84000025.0
26          11938983.0                  NaN             2.140775  84000026.0
27           7978553.0                  NaN             1.297844  84000027.0
28           1845873.0                  NaN             2.308025  84000028.0
29           5027327.0                  NaN             1.509447  84000029.0
30           1245182.0                  NaN             1.434316  84000030.0
31           2695720.0                  NaN             1.036381  84000031.0
32           3043137.0                  NaN             1.731034  84000032.0
33           1728015.0                  NaN             1.414680  84000033.0
34          12694233.0                  NaN             2.608313  84000034.0
35           3079551.0                  NaN             2.056183  84000035.0
36          47244227.0                  NaN             2.612550  84000036.0
37          10765561.0                  NaN             1.317831  84000037.0
38           1485211.0                  NaN             1.433959  84000038.0
39             17542.0                  NaN             1.250000       580.0
40          11310109.0                  NaN             1.811238  84000039.0
41           3838783.0                  NaN             1.506081  84000040.0
42           4319403.0                  NaN             1.430515  84000041.0
43          12148589.0                  NaN             2.364506  84000042.0
44            415664.0                  NaN             1.869054       630.0
45           3680071.0                  NaN             1.869636  84000044.0
46           5822980.0                  NaN             1.648507  84000045.0
47            751549.0                  NaN             1.625663  84000046.0
48           7346127.0                  NaN             1.459825  84000047.0
49          21970307.0                  NaN             1.740799  84000048.0
50           3151927.0                  NaN             0.553442  84000049.0
51           1425517.0                  NaN             1.089520  84000050.0
52             90048.0                  NaN             0.875126       850.0
53           6680238.0                  NaN             1.647702  84000051.0
54           6115030.0                  NaN             1.414560  84000053.0
55           2571730.0                  NaN             1.877963  84000054.0
56           7847462.0                  NaN             1.143275  84000055.0
57            698827.0                  NaN             1.232571  84000056.0

   ISO3   Testing_Rate  Hospitalization_Rate
0   USA   49690.517490                   NaN
1   USA  268752.845006                   NaN
2   ASM    3846.084722                   NaN
3   USA  120377.547307                   NaN
4   USA   96049.113859                   NaN
5   USA  141927.878874                   NaN
6   USA  126227.856252                   NaN
7   USA  209700.902059                   NaN
8   USA  166425.232397                   NaN
9   USA            NaN                   NaN
10  USA  201697.062270                   NaN
11  USA   99996.070349                   NaN
12  USA   75120.365836                   NaN
13  USA            NaN                   NaN
14  GUM   81799.803932                   NaN
15  USA   93808.126723                   NaN
16  USA   38384.278132                   NaN
17  USA  166530.185362                   NaN
18  USA  136466.876672                   NaN
19  USA   44153.537006                   NaN
20  USA   45826.471160                   NaN
21  USA   98344.954969                   NaN
22  USA  133087.979377                   NaN
23  USA  139277.361012                   NaN
24  USA  150359.496368                   NaN
25  USA  286514.362054                   NaN
26  USA  119546.950557                   NaN
27  USA  141472.936532                   NaN
28  USA   62022.197141                   NaN
29  USA   81912.602478                   NaN
30  USA  116505.205010                   NaN
31  USA  139356.330205                   NaN
32  USA   98798.145289                   NaN
33  USA  127086.932444                   NaN
34  USA  142917.827698                   NaN
35  USA  146867.054967                   NaN
36  USA  242856.446694                   NaN
37  USA  102645.640519                   NaN
38  USA  194893.722558                   NaN
39  MNP   31811.257798                   NaN
40  USA   96757.740117                   NaN
41  USA   97013.169922                   NaN
42  USA  102410.439532                   NaN
43  USA   94896.105597                   NaN
44  PRI   13015.147976                   NaN
45  USA  347385.924156                   NaN
46  USA  113095.813828                   NaN
47  USA   84953.524465                   NaN
48  USA  107569.773446                   NaN
49  USA   75770.441326                   NaN
50  USA   98314.669125                   NaN
51  USA  228452.264383                   NaN
52  VIR   83946.750196                   NaN
53  USA   78263.993086                   NaN
54  USA   80303.557778                   NaN
55  USA  143499.947270                   NaN
56  USA  134779.750187                   NaN
57  USA  120745.768100                   NaN

In [3]:
 df1 = df.dropna(axis = "columns")

In [4]:
final_df = df1[df1['ISO3'] == 'USA'] 
    
print('\nResult dataframe :\n', final_df)

Result dataframe :
           Province_State Country_Region          Last_Update  Confirmed  \
0                Alabama             US  2021-04-12 04:30:34     518899
1                 Alaska             US  2021-04-12 04:30:34      64782
3                Arizona             US  2021-04-12 04:30:34     849561
4               Arkansas             US  2021-04-12 04:30:34     332153
5             California             US  2021-04-12 07:30:55    3700471
6               Colorado             US  2021-04-12 04:30:34     478678
7            Connecticut             US  2021-04-12 04:30:34     321586
8               Delaware             US  2021-04-12 04:30:34      98570
9       Diamond Princess             US  2021-04-12 04:30:34         49
10  District of Columbia             US  2021-04-12 04:30:34      45830
11               Florida             US  2021-04-12 04:30:34    2124233
12               Georgia             US  2021-04-12 04:30:34    1073792
13        Grand Princess             US  2021-04-12 04:30:34        103
15                Hawaii             US  2021-04-12 04:30:34      32067
16                 Idaho             US  2021-04-12 04:30:34     183153
17              Illinois             US  2021-04-12 04:30:34    1279663
18               Indiana             US  2021-04-12 04:30:34     698692
19                  Iowa             US  2021-04-12 04:30:34     357019
20                Kansas             US  2021-04-12 04:30:34     305773
21              Kentucky             US  2021-04-12 04:30:34     433085
22             Louisiana             US  2021-04-12 04:30:34     448838
23                 Maine             US  2021-04-12 04:30:34      53960
24              Maryland             US  2021-04-12 04:30:34     426730
25         Massachusetts             US  2021-04-12 04:30:34     659569
26              Michigan             US  2021-04-12 04:30:34     820404
27             Minnesota             US  2021-04-12 04:30:34     542053
28           Mississippi             US  2021-04-12 04:30:34     307449
29              Missouri             US  2021-04-12 04:30:34     588626
30               Montana             US  2021-04-12 04:30:34     106183
31              Nebraska             US  2021-04-12 04:30:34     214207
32                Nevada             US  2021-04-12 04:30:34     308024
33         New Hampshire             US  2021-04-12 04:30:34      88854
34            New Jersey             US  2021-04-12 04:30:34     953490
35            New Mexico             US  2021-04-12 04:30:34     193368
36              New York             US  2021-04-12 04:30:34    1956594
37        North Carolina             US  2021-04-12 04:30:34     929406
38          North Dakota             US  2021-04-12 04:30:34     104745
40                  Ohio             US  2021-04-12 04:30:34    1039455
41              Oklahoma             US  2021-04-12 04:30:34     442805
42                Oregon             US  2021-04-12 04:30:34     170568
43          Pennsylvania             US  2021-04-12 04:30:34    1073924
45          Rhode Island             US  2021-04-12 04:30:34     141097
46        South Carolina             US  2021-04-12 04:30:34     562691
47          South Dakota             US  2021-04-12 04:30:34     119705
48             Tennessee             US  2021-04-12 04:30:34     822085
49                 Texas             US  2021-04-12 04:30:34    2826977
50                  Utah             US  2021-04-12 04:30:34     390104
51               Vermont             US  2021-04-12 04:30:34      21202
53              Virginia             US  2021-04-12 04:30:34     635552
54            Washington             US  2021-04-12 04:30:34     376230
55         West Virginia             US  2021-04-12 04:30:34     146169
56             Wisconsin             US  2021-04-12 04:30:34     645514
57               Wyoming             US  2021-04-12 04:30:34      56873

    Deaths     FIPS         UID ISO3
0    10712      1.0  84000001.0  USA
1      313      2.0  84000002.0  USA
3    17086      4.0  84000004.0  USA
4     5661      5.0  84000005.0  USA
5    60452      6.0  84000006.0  USA
6     6157      8.0  84000008.0  USA
7     7944      9.0  84000009.0  USA
8     1578     10.0  84000010.0  USA
9        0  88888.0  84088888.0  USA
10    1081     11.0  84000011.0  USA
11   34021     12.0  84000012.0  USA
12   19488     13.0  84000013.0  USA
13       3  99999.0  84099999.0  USA
15     471     15.0  84000015.0  USA
16    1993     16.0  84000016.0  USA
17   23793     17.0  84000017.0  USA
18   13148     18.0  84000018.0  USA
19    5857     19.0  84000019.0  USA
20    4933     20.0  84000020.0  USA
21    6250     21.0  84000021.0  USA
22   10216     22.0  84000022.0  USA
23     750     23.0  84000023.0  USA
24    8455     24.0  84000024.0  USA
25   17387     25.0  84000025.0  USA
26   17563     26.0  84000026.0  USA
27    7035     27.0  84000027.0  USA
28    7096     28.0  84000028.0  USA
29    8885     29.0  84000029.0  USA
30    1523     30.0  84000030.0  USA
31    2220     31.0  84000031.0  USA
32    5332     32.0  84000032.0  USA
33    1257     33.0  84000033.0  USA
34   24870     34.0  84000034.0  USA
35    3976     35.0  84000035.0  USA
36   51117     36.0  84000036.0  USA
37   12248     37.0  84000037.0  USA
38    1502     38.0  84000038.0  USA
40   19200     39.0  84000039.0  USA
41    6669     40.0  84000040.0  USA
42    2440     41.0  84000041.0  USA
43   25393     42.0  84000042.0  USA
45    2638     44.0  84000044.0  USA
46    9276     45.0  84000045.0  USA
47    1946     46.0  84000046.0  USA
48   12001     47.0  84000047.0  USA
49   49212     48.0  84000048.0  USA
50    2159     49.0  84000049.0  USA
51     231     50.0  84000050.0  USA
53   10472     51.0  84000051.0  USA
54    5322     53.0  84000053.0  USA
55    2745     54.0  84000054.0  USA
56    7380     55.0  84000055.0  USA
57     701     56.0  84000056.0  USA

In [5]:
print(final_df)

          Province_State Country_Region          Last_Update  Confirmed  \
0                Alabama             US  2021-04-12 04:30:34     518899
1                 Alaska             US  2021-04-12 04:30:34      64782
3                Arizona             US  2021-04-12 04:30:34     849561
4               Arkansas             US  2021-04-12 04:30:34     332153
5             California             US  2021-04-12 07:30:55    3700471
6               Colorado             US  2021-04-12 04:30:34     478678
7            Connecticut             US  2021-04-12 04:30:34     321586
8               Delaware             US  2021-04-12 04:30:34      98570
9       Diamond Princess             US  2021-04-12 04:30:34         49
10  District of Columbia             US  2021-04-12 04:30:34      45830
11               Florida             US  2021-04-12 04:30:34    2124233
12               Georgia             US  2021-04-12 04:30:34    1073792
13        Grand Princess             US  2021-04-12 04:30:34        103
15                Hawaii             US  2021-04-12 04:30:34      32067
16                 Idaho             US  2021-04-12 04:30:34     183153
17              Illinois             US  2021-04-12 04:30:34    1279663
18               Indiana             US  2021-04-12 04:30:34     698692
19                  Iowa             US  2021-04-12 04:30:34     357019
20                Kansas             US  2021-04-12 04:30:34     305773
21              Kentucky             US  2021-04-12 04:30:34     433085
22             Louisiana             US  2021-04-12 04:30:34     448838
23                 Maine             US  2021-04-12 04:30:34      53960
24              Maryland             US  2021-04-12 04:30:34     426730
25         Massachusetts             US  2021-04-12 04:30:34     659569
26              Michigan             US  2021-04-12 04:30:34     820404
27             Minnesota             US  2021-04-12 04:30:34     542053
28           Mississippi             US  2021-04-12 04:30:34     307449
29              Missouri             US  2021-04-12 04:30:34     588626
30               Montana             US  2021-04-12 04:30:34     106183
31              Nebraska             US  2021-04-12 04:30:34     214207
32                Nevada             US  2021-04-12 04:30:34     308024
33         New Hampshire             US  2021-04-12 04:30:34      88854
34            New Jersey             US  2021-04-12 04:30:34     953490
35            New Mexico             US  2021-04-12 04:30:34     193368
36              New York             US  2021-04-12 04:30:34    1956594
37        North Carolina             US  2021-04-12 04:30:34     929406
38          North Dakota             US  2021-04-12 04:30:34     104745
40                  Ohio             US  2021-04-12 04:30:34    1039455
41              Oklahoma             US  2021-04-12 04:30:34     442805
42                Oregon             US  2021-04-12 04:30:34     170568
43          Pennsylvania             US  2021-04-12 04:30:34    1073924
45          Rhode Island             US  2021-04-12 04:30:34     141097
46        South Carolina             US  2021-04-12 04:30:34     562691
47          South Dakota             US  2021-04-12 04:30:34     119705
48             Tennessee             US  2021-04-12 04:30:34     822085
49                 Texas             US  2021-04-12 04:30:34    2826977
50                  Utah             US  2021-04-12 04:30:34     390104
51               Vermont             US  2021-04-12 04:30:34      21202
53              Virginia             US  2021-04-12 04:30:34     635552
54            Washington             US  2021-04-12 04:30:34     376230
55         West Virginia             US  2021-04-12 04:30:34     146169
56             Wisconsin             US  2021-04-12 04:30:34     645514
57               Wyoming             US  2021-04-12 04:30:34      56873

    Deaths     FIPS         UID ISO3
0    10712      1.0  84000001.0  USA
1      313      2.0  84000002.0  USA
3    17086      4.0  84000004.0  USA
4     5661      5.0  84000005.0  USA
5    60452      6.0  84000006.0  USA
6     6157      8.0  84000008.0  USA
7     7944      9.0  84000009.0  USA
8     1578     10.0  84000010.0  USA
9        0  88888.0  84088888.0  USA
10    1081     11.0  84000011.0  USA
11   34021     12.0  84000012.0  USA
12   19488     13.0  84000013.0  USA
13       3  99999.0  84099999.0  USA
15     471     15.0  84000015.0  USA
16    1993     16.0  84000016.0  USA
17   23793     17.0  84000017.0  USA
18   13148     18.0  84000018.0  USA
19    5857     19.0  84000019.0  USA
20    4933     20.0  84000020.0  USA
21    6250     21.0  84000021.0  USA
22   10216     22.0  84000022.0  USA
23     750     23.0  84000023.0  USA
24    8455     24.0  84000024.0  USA
25   17387     25.0  84000025.0  USA
26   17563     26.0  84000026.0  USA
27    7035     27.0  84000027.0  USA
28    7096     28.0  84000028.0  USA
29    8885     29.0  84000029.0  USA
30    1523     30.0  84000030.0  USA
31    2220     31.0  84000031.0  USA
32    5332     32.0  84000032.0  USA
33    1257     33.0  84000033.0  USA
34   24870     34.0  84000034.0  USA
35    3976     35.0  84000035.0  USA
36   51117     36.0  84000036.0  USA
37   12248     37.0  84000037.0  USA
38    1502     38.0  84000038.0  USA
40   19200     39.0  84000039.0  USA
41    6669     40.0  84000040.0  USA
42    2440     41.0  84000041.0  USA
43   25393     42.0  84000042.0  USA
45    2638     44.0  84000044.0  USA
46    9276     45.0  84000045.0  USA
47    1946     46.0  84000046.0  USA
48   12001     47.0  84000047.0  USA
49   49212     48.0  84000048.0  USA
50    2159     49.0  84000049.0  USA
51     231     50.0  84000050.0  USA
53   10472     51.0  84000051.0  USA
54    5322     53.0  84000053.0  USA
55    2745     54.0  84000054.0  USA
56    7380     55.0  84000055.0  USA
57     701     56.0  84000056.0  USA

In [6]:
final_df.sort_values(by= 'Confirmed', ascending = False)

,Province_State,Country_Region,Last_Update,Confirmed,Deaths,FIPS,UID,ISO3
5,California,US,2021-04-12 07:30:55,3700471,60452,6.0,84000006.0,USA
49,Texas,US,2021-04-12 04:30:34,2826977,49212,48.0,84000048.0,USA
11,Florida,US,2021-04-12 04:30:34,2124233,34021,12.0,84000012.0,USA
36,New York,US,2021-04-12 04:30:34,1956594,51117,36.0,84000036.0,USA
17,Illinois,US,2021-04-12 04:30:34,1279663,23793,17.0,84000017.0,USA
43,Pennsylvania,US,2021-04-12 04:30:34,1073924,25393,42.0,84000042.0,USA
12,Georgia,US,2021-04-12 04:30:34,1073792,19488,13.0,84000013.0,USA
40,Ohio,US,2021-04-12 04:30:34,1039455,19200,39.0,84000039.0,USA
34,New Jersey,US,2021-04-12 04:30:34,953490,24870,34.0,84000034.0,USA
37,North Carolina,US,2021-04-12 04:30:34,929406,12248,37.0,84000037.0,USA
3,Arizona,US,2021-04-12 04:30:34,849561,17086,4.0,84000004.0,USA
48,Tennessee,US,2021-04-12 04:30:34,822085,12001,47.0,84000047.0,USA
26,Michigan,US,2021-04-12 04:30:34,820404,17563,26.0,84000026.0,USA
18,Indiana,US,2021-04-12 04:30:34,698692,13148,18.0,84000018.0,USA
25,Massachusetts,US,2021-04-12 04:30:34,659569,17387,25.0,84000025.0,USA
56,Wisconsin,US,2021-04-12 04:30:34,645514,7380,55.0,84000055.0,USA
53,Virginia,US,2021-04-12 04:30:34,635552,10472,51.0,84000051.0,USA
29,Missouri,US,2021-04-12 04:30:34,588626,8885,29.0,84000029.0,USA
46,South Carolina,US,2021-04-12 04:30:34,562691,9276,45.0,84000045.0,USA
27,Minnesota,US,2021-04-12 04:30:34,542053,7035,27.0,84000027.0,USA
0,Alabama,US,2021-04-12 04:30:34,518899,10712,1.0,84000001.0,USA
6,Colorado,US,2021-04-12 04:30:34,478678,6157,8.0,84000008.0,USA
22,Louisiana,US,2021-04-12 04:30:34,448838,10216,22.0,84000022.0,USA
41,Oklahoma,US,2021-04-12 04:30:34,442805,6669,40.0,84000040.0,USA
21,Kentucky,US,2021-04-12 04:30:34,433085,6250,21.0,84000021.0,USA
24,Maryland,US,2021-04-12 04:30:34,426730,8455,24.0,84000024.0,USA
50,Utah,US,2021-04-12 04:30:34,390104,2159,49.0,84000049.0,USA
54,Washington,US,2021-04-12 04:30:34,376230,5322,53.0,84000053.0,USA
19,Iowa,US,2021-04-12 04:30:34,357019,5857,19.0,84000019.0,USA
4,Arkansas,US,2021-04-12 04:30:34,332153,5661,5.0,84000005.0,USA
7,Connecticut,US,2021-04-12 04:30:34,321586,7944,9.0,84000009.0,USA
32,Nevada,US,2021-04-12 04:30:34,308024,5332,32.0,84000032.0,USA
28,Mississippi,US,2021-04-12 04:30:34,307449,7096,28.0,84000028.0,USA
20,Kansas,US,2021-04-12 04:30:34,305773,4933,20.0,84000020.0,USA
31,Nebraska,US,2021-04-12 04:30:34,214207,2220,31.0,84000031.0,USA
35,New Mexico,US,2021-04-12 04:30:34,193368,3976,35.0,84000035.0,USA
16,Idaho,US,2021-04-12 04:30:34,183153,1993,16.0,84000016.0,USA
42,Oregon,US,2021-04-12 04:30:34,170568,2440,41.0,84000041.0,USA
55,West Virginia,US,2021-04-12 04:30:34,146169,2745,54.0,84000054.0,USA
45,Rhode Island,US,2021-04-12 04:30:34,141097,2638,44.0,84000044.0,USA
47,South Dakota,US,2021-04-12 04:30:34,119705,1946,46.0,84000046.0,USA
30,Montana,US,2021-04-12 04:30:34,106183,1523,30.0,84000030.0,USA
38,North Dakota,US,2021-04-12 04:30:34,104745,1502,38.0,84000038.0,USA
8,Delaware,US,2021-04-12 04:30:34,98570,1578,10.0,84000010.0,USA
33,New Hampshire,US,2021-04-12 04:30:34,88854,1257,33.0,84000033.0,USA
1,Alaska,US,2021-04-12 04:30:34,64782,313,2.0,84000002.0,USA
57,Wyoming,US,2021-04-12 04:30:34,56873,701,56.0,84000056.0,USA
23,Maine,US,2021-04-12 04:30:34,53960,750,23.0,84000023.0,USA
10,District of Columbia,US,2021-04-12 04:30:34,45830,1081,11.0,84000011.0,USA
15,Hawaii,US,2021-04-12 04:30:34,32067,471,15.0,84000015.0,USA
51,Vermont,US,2021-04-12 04:30:34,21202,231,50.0,84000050.0,USA
13,Grand Princess,US,2021-04-12 04:30:34,103,3,99999.0,84099999.0,USA
9,Diamond Princess,US,2021-04-12 04:30:34,49,0,88888.0,84088888.0,USA

In [7]:
final_df.sort_values(by= 'Deaths', ascending = False)

,Province_State,Country_Region,Last_Update,Confirmed,Deaths,FIPS,UID,ISO3
5,California,US,2021-04-12 07:30:55,3700471,60452,6.0,84000006.0,USA
36,New York,US,2021-04-12 04:30:34,1956594,51117,36.0,84000036.0,USA
49,Texas,US,2021-04-12 04:30:34,2826977,49212,48.0,84000048.0,USA
11,Florida,US,2021-04-12 04:30:34,2124233,34021,12.0,84000012.0,USA
43,Pennsylvania,US,2021-04-12 04:30:34,1073924,25393,42.0,84000042.0,USA
34,New Jersey,US,2021-04-12 04:30:34,953490,24870,34.0,84000034.0,USA
17,Illinois,US,2021-04-12 04:30:34,1279663,23793,17.0,84000017.0,USA
12,Georgia,US,2021-04-12 04:30:34,1073792,19488,13.0,84000013.0,USA
40,Ohio,US,2021-04-12 04:30:34,1039455,19200,39.0,84000039.0,USA
26,Michigan,US,2021-04-12 04:30:34,820404,17563,26.0,84000026.0,USA
25,Massachusetts,US,2021-04-12 04:30:34,659569,17387,25.0,84000025.0,USA
3,Arizona,US,2021-04-12 04:30:34,849561,17086,4.0,84000004.0,USA
18,Indiana,US,2021-04-12 04:30:34,698692,13148,18.0,84000018.0,USA
37,North Carolina,US,2021-04-12 04:30:34,929406,12248,37.0,84000037.0,USA
48,Tennessee,US,2021-04-12 04:30:34,822085,12001,47.0,84000047.0,USA
0,Alabama,US,2021-04-12 04:30:34,518899,10712,1.0,84000001.0,USA
53,Virginia,US,2021-04-12 04:30:34,635552,10472,51.0,84000051.0,USA
22,Louisiana,US,2021-04-12 04:30:34,448838,10216,22.0,84000022.0,USA
46,South Carolina,US,2021-04-12 04:30:34,562691,9276,45.0,84000045.0,USA
29,Missouri,US,2021-04-12 04:30:34,588626,8885,29.0,84000029.0,USA
24,Maryland,US,2021-04-12 04:30:34,426730,8455,24.0,84000024.0,USA
7,Connecticut,US,2021-04-12 04:30:34,321586,7944,9.0,84000009.0,USA
56,Wisconsin,US,2021-04-12 04:30:34,645514,7380,55.0,84000055.0,USA
28,Mississippi,US,2021-04-12 04:30:34,307449,7096,28.0,84000028.0,USA
27,Minnesota,US,2021-04-12 04:30:34,542053,7035,27.0,84000027.0,USA
41,Oklahoma,US,2021-04-12 04:30:34,442805,6669,40.0,84000040.0,USA
21,Kentucky,US,2021-04-12 04:30:34,433085,6250,21.0,84000021.0,USA
6,Colorado,US,2021-04-12 04:30:34,478678,6157,8.0,84000008.0,USA
19,Iowa,US,2021-04-12 04:30:34,357019,5857,19.0,84000019.0,USA
4,Arkansas,US,2021-04-12 04:30:34,332153,5661,5.0,84000005.0,USA
32,Nevada,US,2021-04-12 04:30:34,308024,5332,32.0,84000032.0,USA
54,Washington,US,2021-04-12 04:30:34,376230,5322,53.0,84000053.0,USA
20,Kansas,US,2021-04-12 04:30:34,305773,4933,20.0,84000020.0,USA
35,New Mexico,US,2021-04-12 04:30:34,193368,3976,35.0,84000035.0,USA
55,West Virginia,US,2021-04-12 04:30:34,146169,2745,54.0,84000054.0,USA
45,Rhode Island,US,2021-04-12 04:30:34,141097,2638,44.0,84000044.0,USA
42,Oregon,US,2021-04-12 04:30:34,170568,2440,41.0,84000041.0,USA
31,Nebraska,US,2021-04-12 04:30:34,214207,2220,31.0,84000031.0,USA
50,Utah,US,2021-04-12 04:30:34,390104,2159,49.0,84000049.0,USA
16,Idaho,US,2021-04-12 04:30:34,183153,1993,16.0,84000016.0,USA
47,South Dakota,US,2021-04-12 04:30:34,119705,1946,46.0,84000046.0,USA
8,Delaware,US,2021-04-12 04:30:34,98570,1578,10.0,84000010.0,USA
30,Montana,US,2021-04-12 04:30:34,106183,1523,30.0,84000030.0,USA
38,North Dakota,US,2021-04-12 04:30:34,104745,1502,38.0,84000038.0,USA
33,New Hampshire,US,2021-04-12 04:30:34,88854,1257,33.0,84000033.0,USA
10,District of Columbia,US,2021-04-12 04:30:34,45830,1081,11.0,84000011.0,USA
23,Maine,US,2021-04-12 04:30:34,53960,750,23.0,84000023.0,USA
57,Wyoming,US,2021-04-12 04:30:34,56873,701,56.0,84000056.0,USA
15,Hawaii,US,2021-04-12 04:30:34,32067,471,15.0,84000015.0,USA
1,Alaska,US,2021-04-12 04:30:34,64782,313,2.0,84000002.0,USA
51,Vermont,US,2021-04-12 04:30:34,21202,231,50.0,84000050.0,USA
13,Grand Princess,US,2021-04-12 04:30:34,103,3,99999.0,84099999.0,USA
9,Diamond Princess,US,2021-04-12 04:30:34,49,0,88888.0,84088888.0,USA

In [8]:
Confirmed_df = df1[df1['ISO3'] == 'USA'] 
    
print('\nResult dataframe :\n', Confirmed_df)

Result dataframe :
           Province_State Country_Region          Last_Update  Confirmed  \
0                Alabama             US  2021-04-12 04:30:34     518899
1                 Alaska             US  2021-04-12 04:30:34      64782
3                Arizona             US  2021-04-12 04:30:34     849561
4               Arkansas             US  2021-04-12 04:30:34     332153
5             California             US  2021-04-12 07:30:55    3700471
6               Colorado             US  2021-04-12 04:30:34     478678
7            Connecticut             US  2021-04-12 04:30:34     321586
8               Delaware             US  2021-04-12 04:30:34      98570
9       Diamond Princess             US  2021-04-12 04:30:34         49
10  District of Columbia             US  2021-04-12 04:30:34      45830
11               Florida             US  2021-04-12 04:30:34    2124233
12               Georgia             US  2021-04-12 04:30:34    1073792
13        Grand Princess             US  2021-04-12 04:30:34        103
15                Hawaii             US  2021-04-12 04:30:34      32067
16                 Idaho             US  2021-04-12 04:30:34     183153
17              Illinois             US  2021-04-12 04:30:34    1279663
18               Indiana             US  2021-04-12 04:30:34     698692
19                  Iowa             US  2021-04-12 04:30:34     357019
20                Kansas             US  2021-04-12 04:30:34     305773
21              Kentucky             US  2021-04-12 04:30:34     433085
22             Louisiana             US  2021-04-12 04:30:34     448838
23                 Maine             US  2021-04-12 04:30:34      53960
24              Maryland             US  2021-04-12 04:30:34     426730
25         Massachusetts             US  2021-04-12 04:30:34     659569
26              Michigan             US  2021-04-12 04:30:34     820404
27             Minnesota             US  2021-04-12 04:30:34     542053
28           Mississippi             US  2021-04-12 04:30:34     307449
29              Missouri             US  2021-04-12 04:30:34     588626
30               Montana             US  2021-04-12 04:30:34     106183
31              Nebraska             US  2021-04-12 04:30:34     214207
32                Nevada             US  2021-04-12 04:30:34     308024
33         New Hampshire             US  2021-04-12 04:30:34      88854
34            New Jersey             US  2021-04-12 04:30:34     953490
35            New Mexico             US  2021-04-12 04:30:34     193368
36              New York             US  2021-04-12 04:30:34    1956594
37        North Carolina             US  2021-04-12 04:30:34     929406
38          North Dakota             US  2021-04-12 04:30:34     104745
40                  Ohio             US  2021-04-12 04:30:34    1039455
41              Oklahoma             US  2021-04-12 04:30:34     442805
42                Oregon             US  2021-04-12 04:30:34     170568
43          Pennsylvania             US  2021-04-12 04:30:34    1073924
45          Rhode Island             US  2021-04-12 04:30:34     141097
46        South Carolina             US  2021-04-12 04:30:34     562691
47          South Dakota             US  2021-04-12 04:30:34     119705
48             Tennessee             US  2021-04-12 04:30:34     822085
49                 Texas             US  2021-04-12 04:30:34    2826977
50                  Utah             US  2021-04-12 04:30:34     390104
51               Vermont             US  2021-04-12 04:30:34      21202
53              Virginia             US  2021-04-12 04:30:34     635552
54            Washington             US  2021-04-12 04:30:34     376230
55         West Virginia             US  2021-04-12 04:30:34     146169
56             Wisconsin             US  2021-04-12 04:30:34     645514
57               Wyoming             US  2021-04-12 04:30:34      56873

    Deaths     FIPS         UID ISO3
0    10712      1.0  84000001.0  USA
1      313      2.0  84000002.0  USA
3    17086      4.0  84000004.0  USA
4     5661      5.0  84000005.0  USA
5    60452      6.0  84000006.0  USA
6     6157      8.0  84000008.0  USA
7     7944      9.0  84000009.0  USA
8     1578     10.0  84000010.0  USA
9        0  88888.0  84088888.0  USA
10    1081     11.0  84000011.0  USA
11   34021     12.0  84000012.0  USA
12   19488     13.0  84000013.0  USA
13       3  99999.0  84099999.0  USA
15     471     15.0  84000015.0  USA
16    1993     16.0  84000016.0  USA
17   23793     17.0  84000017.0  USA
18   13148     18.0  84000018.0  USA
19    5857     19.0  84000019.0  USA
20    4933     20.0  84000020.0  USA
21    6250     21.0  84000021.0  USA
22   10216     22.0  84000022.0  USA
23     750     23.0  84000023.0  USA
24    8455     24.0  84000024.0  USA
25   17387     25.0  84000025.0  USA
26   17563     26.0  84000026.0  USA
27    7035     27.0  84000027.0  USA
28    7096     28.0  84000028.0  USA
29    8885     29.0  84000029.0  USA
30    1523     30.0  84000030.0  USA
31    2220     31.0  84000031.0  USA
32    5332     32.0  84000032.0  USA
33    1257     33.0  84000033.0  USA
34   24870     34.0  84000034.0  USA
35    3976     35.0  84000035.0  USA
36   51117     36.0  84000036.0  USA
37   12248     37.0  84000037.0  USA
38    1502     38.0  84000038.0  USA
40   19200     39.0  84000039.0  USA
41    6669     40.0  84000040.0  USA
42    2440     41.0  84000041.0  USA
43   25393     42.0  84000042.0  USA
45    2638     44.0  84000044.0  USA
46    9276     45.0  84000045.0  USA
47    1946     46.0  84000046.0  USA
48   12001     47.0  84000047.0  USA
49   49212     48.0  84000048.0  USA
50    2159     49.0  84000049.0  USA
51     231     50.0  84000050.0  USA
53   10472     51.0  84000051.0  USA
54    5322     53.0  84000053.0  USA
55    2745     54.0  84000054.0  USA
56    7380     55.0  84000055.0  USA
57     701     56.0  84000056.0  USA

In [9]:
Confirmed_df.nlargest(3,'Confirmed')

,Province_State,Country_Region,Last_Update,Confirmed,Deaths,FIPS,UID,ISO3
5,California,US,2021-04-12 07:30:55,3700471,60452,6.0,84000006.0,USA
49,Texas,US,2021-04-12 04:30:34,2826977,49212,48.0,84000048.0,USA
11,Florida,US,2021-04-12 04:30:34,2124233,34021,12.0,84000012.0,USA

In [10]:
Deaths_df = df1[df1['ISO3'] == 'USA'] 
    
print('\nResult dataframe :\n', Deaths_df)

Result dataframe :
           Province_State Country_Region          Last_Update  Confirmed  \
0                Alabama             US  2021-04-12 04:30:34     518899
1                 Alaska             US  2021-04-12 04:30:34      64782
3                Arizona             US  2021-04-12 04:30:34     849561
4               Arkansas             US  2021-04-12 04:30:34     332153
5             California             US  2021-04-12 07:30:55    3700471
6               Colorado             US  2021-04-12 04:30:34     478678
7            Connecticut             US  2021-04-12 04:30:34     321586
8               Delaware             US  2021-04-12 04:30:34      98570
9       Diamond Princess             US  2021-04-12 04:30:34         49
10  District of Columbia             US  2021-04-12 04:30:34      45830
11               Florida             US  2021-04-12 04:30:34    2124233
12               Georgia             US  2021-04-12 04:30:34    1073792
13        Grand Princess             US  2021-04-12 04:30:34        103
15                Hawaii             US  2021-04-12 04:30:34      32067
16                 Idaho             US  2021-04-12 04:30:34     183153
17              Illinois             US  2021-04-12 04:30:34    1279663
18               Indiana             US  2021-04-12 04:30:34     698692
19                  Iowa             US  2021-04-12 04:30:34     357019
20                Kansas             US  2021-04-12 04:30:34     305773
21              Kentucky             US  2021-04-12 04:30:34     433085
22             Louisiana             US  2021-04-12 04:30:34     448838
23                 Maine             US  2021-04-12 04:30:34      53960
24              Maryland             US  2021-04-12 04:30:34     426730
25         Massachusetts             US  2021-04-12 04:30:34     659569
26              Michigan             US  2021-04-12 04:30:34     820404
27             Minnesota             US  2021-04-12 04:30:34     542053
28           Mississippi             US  2021-04-12 04:30:34     307449
29              Missouri             US  2021-04-12 04:30:34     588626
30               Montana             US  2021-04-12 04:30:34     106183
31              Nebraska             US  2021-04-12 04:30:34     214207
32                Nevada             US  2021-04-12 04:30:34     308024
33         New Hampshire             US  2021-04-12 04:30:34      88854
34            New Jersey             US  2021-04-12 04:30:34     953490
35            New Mexico             US  2021-04-12 04:30:34     193368
36              New York             US  2021-04-12 04:30:34    1956594
37        North Carolina             US  2021-04-12 04:30:34     929406
38          North Dakota             US  2021-04-12 04:30:34     104745
40                  Ohio             US  2021-04-12 04:30:34    1039455
41              Oklahoma             US  2021-04-12 04:30:34     442805
42                Oregon             US  2021-04-12 04:30:34     170568
43          Pennsylvania             US  2021-04-12 04:30:34    1073924
45          Rhode Island             US  2021-04-12 04:30:34     141097
46        South Carolina             US  2021-04-12 04:30:34     562691
47          South Dakota             US  2021-04-12 04:30:34     119705
48             Tennessee             US  2021-04-12 04:30:34     822085
49                 Texas             US  2021-04-12 04:30:34    2826977
50                  Utah             US  2021-04-12 04:30:34     390104
51               Vermont             US  2021-04-12 04:30:34      21202
53              Virginia             US  2021-04-12 04:30:34     635552
54            Washington             US  2021-04-12 04:30:34     376230
55         West Virginia             US  2021-04-12 04:30:34     146169
56             Wisconsin             US  2021-04-12 04:30:34     645514
57               Wyoming             US  2021-04-12 04:30:34      56873

    Deaths     FIPS         UID ISO3
0    10712      1.0  84000001.0  USA
1      313      2.0  84000002.0  USA
3    17086      4.0  84000004.0  USA
4     5661      5.0  84000005.0  USA
5    60452      6.0  84000006.0  USA
6     6157      8.0  84000008.0  USA
7     7944      9.0  84000009.0  USA
8     1578     10.0  84000010.0  USA
9        0  88888.0  84088888.0  USA
10    1081     11.0  84000011.0  USA
11   34021     12.0  84000012.0  USA
12   19488     13.0  84000013.0  USA
13       3  99999.0  84099999.0  USA
15     471     15.0  84000015.0  USA
16    1993     16.0  84000016.0  USA
17   23793     17.0  84000017.0  USA
18   13148     18.0  84000018.0  USA
19    5857     19.0  84000019.0  USA
20    4933     20.0  84000020.0  USA
21    6250     21.0  84000021.0  USA
22   10216     22.0  84000022.0  USA
23     750     23.0  84000023.0  USA
24    8455     24.0  84000024.0  USA
25   17387     25.0  84000025.0  USA
26   17563     26.0  84000026.0  USA
27    7035     27.0  84000027.0  USA
28    7096     28.0  84000028.0  USA
29    8885     29.0  84000029.0  USA
30    1523     30.0  84000030.0  USA
31    2220     31.0  84000031.0  USA
32    5332     32.0  84000032.0  USA
33    1257     33.0  84000033.0  USA
34   24870     34.0  84000034.0  USA
35    3976     35.0  84000035.0  USA
36   51117     36.0  84000036.0  USA
37   12248     37.0  84000037.0  USA
38    1502     38.0  84000038.0  USA
40   19200     39.0  84000039.0  USA
41    6669     40.0  84000040.0  USA
42    2440     41.0  84000041.0  USA
43   25393     42.0  84000042.0  USA
45    2638     44.0  84000044.0  USA
46    9276     45.0  84000045.0  USA
47    1946     46.0  84000046.0  USA
48   12001     47.0  84000047.0  USA
49   49212     48.0  84000048.0  USA
50    2159     49.0  84000049.0  USA
51     231     50.0  84000050.0  USA
53   10472     51.0  84000051.0  USA
54    5322     53.0  84000053.0  USA
55    2745     54.0  84000054.0  USA
56    7380     55.0  84000055.0  USA
57     701     56.0  84000056.0  USA

In [11]:
Deaths_df.nlargest(3,'Deaths')

,Province_State,Country_Region,Last_Update,Confirmed,Deaths,FIPS,UID,ISO3
5,California,US,2021-04-12 07:30:55,3700471,60452,6.0,84000006.0,USA
36,New York,US,2021-04-12 04:30:34,1956594,51117,36.0,84000036.0,USA
49,Texas,US,2021-04-12 04:30:34,2826977,49212,48.0,84000048.0,USA

In [12]:
final_df.to_csv('C:\\Users\\Logan\Covid19.csv', index = False)

In [13]:
pwd%

'C:\\Users\\Logan'

In [14]:
Covid19_Dimension = final_df[['Province_State', 'Country_Region', 'Last_Update']]

In [15]:
print(Covid19_Dimension)

          Province_State Country_Region          Last_Update
0                Alabama             US  2021-04-12 04:30:34
1                 Alaska             US  2021-04-12 04:30:34
3                Arizona             US  2021-04-12 04:30:34
4               Arkansas             US  2021-04-12 04:30:34
5             California             US  2021-04-12 07:30:55
6               Colorado             US  2021-04-12 04:30:34
7            Connecticut             US  2021-04-12 04:30:34
8               Delaware             US  2021-04-12 04:30:34
9       Diamond Princess             US  2021-04-12 04:30:34
10  District of Columbia             US  2021-04-12 04:30:34
11               Florida             US  2021-04-12 04:30:34
12               Georgia             US  2021-04-12 04:30:34
13        Grand Princess             US  2021-04-12 04:30:34
15                Hawaii             US  2021-04-12 04:30:34
16                 Idaho             US  2021-04-12 04:30:34
17              Illinois             US  2021-04-12 04:30:34
18               Indiana             US  2021-04-12 04:30:34
19                  Iowa             US  2021-04-12 04:30:34
20                Kansas             US  2021-04-12 04:30:34
21              Kentucky             US  2021-04-12 04:30:34
22             Louisiana             US  2021-04-12 04:30:34
23                 Maine             US  2021-04-12 04:30:34
24              Maryland             US  2021-04-12 04:30:34
25         Massachusetts             US  2021-04-12 04:30:34
26              Michigan             US  2021-04-12 04:30:34
27             Minnesota             US  2021-04-12 04:30:34
28           Mississippi             US  2021-04-12 04:30:34
29              Missouri             US  2021-04-12 04:30:34
30               Montana             US  2021-04-12 04:30:34
31              Nebraska             US  2021-04-12 04:30:34
32                Nevada             US  2021-04-12 04:30:34
33         New Hampshire             US  2021-04-12 04:30:34
34            New Jersey             US  2021-04-12 04:30:34
35            New Mexico             US  2021-04-12 04:30:34
36              New York             US  2021-04-12 04:30:34
37        North Carolina             US  2021-04-12 04:30:34
38          North Dakota             US  2021-04-12 04:30:34
40                  Ohio             US  2021-04-12 04:30:34
41              Oklahoma             US  2021-04-12 04:30:34
42                Oregon             US  2021-04-12 04:30:34
43          Pennsylvania             US  2021-04-12 04:30:34
45          Rhode Island             US  2021-04-12 04:30:34
46        South Carolina             US  2021-04-12 04:30:34
47          South Dakota             US  2021-04-12 04:30:34
48             Tennessee             US  2021-04-12 04:30:34
49                 Texas             US  2021-04-12 04:30:34
50                  Utah             US  2021-04-12 04:30:34
51               Vermont             US  2021-04-12 04:30:34
53              Virginia             US  2021-04-12 04:30:34
54            Washington             US  2021-04-12 04:30:34
55         West Virginia             US  2021-04-12 04:30:34
56             Wisconsin             US  2021-04-12 04:30:34
57               Wyoming             US  2021-04-12 04:30:34

In [16]:
print(final_df)

          Province_State Country_Region          Last_Update  Confirmed  \
0                Alabama             US  2021-04-12 04:30:34     518899
1                 Alaska             US  2021-04-12 04:30:34      64782
3                Arizona             US  2021-04-12 04:30:34     849561
4               Arkansas             US  2021-04-12 04:30:34     332153
5             California             US  2021-04-12 07:30:55    3700471
6               Colorado             US  2021-04-12 04:30:34     478678
7            Connecticut             US  2021-04-12 04:30:34     321586
8               Delaware             US  2021-04-12 04:30:34      98570
9       Diamond Princess             US  2021-04-12 04:30:34         49
10  District of Columbia             US  2021-04-12 04:30:34      45830
11               Florida             US  2021-04-12 04:30:34    2124233
12               Georgia             US  2021-04-12 04:30:34    1073792
13        Grand Princess             US  2021-04-12 04:30:34        103
15                Hawaii             US  2021-04-12 04:30:34      32067
16                 Idaho             US  2021-04-12 04:30:34     183153
17              Illinois             US  2021-04-12 04:30:34    1279663
18               Indiana             US  2021-04-12 04:30:34     698692
19                  Iowa             US  2021-04-12 04:30:34     357019
20                Kansas             US  2021-04-12 04:30:34     305773
21              Kentucky             US  2021-04-12 04:30:34     433085
22             Louisiana             US  2021-04-12 04:30:34     448838
23                 Maine             US  2021-04-12 04:30:34      53960
24              Maryland             US  2021-04-12 04:30:34     426730
25         Massachusetts             US  2021-04-12 04:30:34     659569
26              Michigan             US  2021-04-12 04:30:34     820404
27             Minnesota             US  2021-04-12 04:30:34     542053
28           Mississippi             US  2021-04-12 04:30:34     307449
29              Missouri             US  2021-04-12 04:30:34     588626
30               Montana             US  2021-04-12 04:30:34     106183
31              Nebraska             US  2021-04-12 04:30:34     214207
32                Nevada             US  2021-04-12 04:30:34     308024
33         New Hampshire             US  2021-04-12 04:30:34      88854
34            New Jersey             US  2021-04-12 04:30:34     953490
35            New Mexico             US  2021-04-12 04:30:34     193368
36              New York             US  2021-04-12 04:30:34    1956594
37        North Carolina             US  2021-04-12 04:30:34     929406
38          North Dakota             US  2021-04-12 04:30:34     104745
40                  Ohio             US  2021-04-12 04:30:34    1039455
41              Oklahoma             US  2021-04-12 04:30:34     442805
42                Oregon             US  2021-04-12 04:30:34     170568
43          Pennsylvania             US  2021-04-12 04:30:34    1073924
45          Rhode Island             US  2021-04-12 04:30:34     141097
46        South Carolina             US  2021-04-12 04:30:34     562691
47          South Dakota             US  2021-04-12 04:30:34     119705
48             Tennessee             US  2021-04-12 04:30:34     822085
49                 Texas             US  2021-04-12 04:30:34    2826977
50                  Utah             US  2021-04-12 04:30:34     390104
51               Vermont             US  2021-04-12 04:30:34      21202
53              Virginia             US  2021-04-12 04:30:34     635552
54            Washington             US  2021-04-12 04:30:34     376230
55         West Virginia             US  2021-04-12 04:30:34     146169
56             Wisconsin             US  2021-04-12 04:30:34     645514
57               Wyoming             US  2021-04-12 04:30:34      56873

    Deaths     FIPS         UID ISO3
0    10712      1.0  84000001.0  USA
1      313      2.0  84000002.0  USA
3    17086      4.0  84000004.0  USA
4     5661      5.0  84000005.0  USA
5    60452      6.0  84000006.0  USA
6     6157      8.0  84000008.0  USA
7     7944      9.0  84000009.0  USA
8     1578     10.0  84000010.0  USA
9        0  88888.0  84088888.0  USA
10    1081     11.0  84000011.0  USA
11   34021     12.0  84000012.0  USA
12   19488     13.0  84000013.0  USA
13       3  99999.0  84099999.0  USA
15     471     15.0  84000015.0  USA
16    1993     16.0  84000016.0  USA
17   23793     17.0  84000017.0  USA
18   13148     18.0  84000018.0  USA
19    5857     19.0  84000019.0  USA
20    4933     20.0  84000020.0  USA
21    6250     21.0  84000021.0  USA
22   10216     22.0  84000022.0  USA
23     750     23.0  84000023.0  USA
24    8455     24.0  84000024.0  USA
25   17387     25.0  84000025.0  USA
26   17563     26.0  84000026.0  USA
27    7035     27.0  84000027.0  USA
28    7096     28.0  84000028.0  USA
29    8885     29.0  84000029.0  USA
30    1523     30.0  84000030.0  USA
31    2220     31.0  84000031.0  USA
32    5332     32.0  84000032.0  USA
33    1257     33.0  84000033.0  USA
34   24870     34.0  84000034.0  USA
35    3976     35.0  84000035.0  USA
36   51117     36.0  84000036.0  USA
37   12248     37.0  84000037.0  USA
38    1502     38.0  84000038.0  USA
40   19200     39.0  84000039.0  USA
41    6669     40.0  84000040.0  USA
42    2440     41.0  84000041.0  USA
43   25393     42.0  84000042.0  USA
45    2638     44.0  84000044.0  USA
46    9276     45.0  84000045.0  USA
47    1946     46.0  84000046.0  USA
48   12001     47.0  84000047.0  USA
49   49212     48.0  84000048.0  USA
50    2159     49.0  84000049.0  USA
51     231     50.0  84000050.0  USA
53   10472     51.0  84000051.0  USA
54    5322     53.0  84000053.0  USA
55    2745     54.0  84000054.0  USA
56    7380     55.0  84000055.0  USA
57     701     56.0  84000056.0  USA

In [17]:
Covid19_Dimension.to_csv('C:\\Users\\Logan\Covid19_Dimension.csv', index = False)

In [18]:
Covid19_Fact = final_df[['Province_State', 'Country_Region', 'Last_Update', 'Confirmed', 'Deaths']]

In [19]:
print(Covid19_Fact)

          Province_State Country_Region          Last_Update  Confirmed  \
0                Alabama             US  2021-04-12 04:30:34     518899
1                 Alaska             US  2021-04-12 04:30:34      64782
3                Arizona             US  2021-04-12 04:30:34     849561
4               Arkansas             US  2021-04-12 04:30:34     332153
5             California             US  2021-04-12 07:30:55    3700471
6               Colorado             US  2021-04-12 04:30:34     478678
7            Connecticut             US  2021-04-12 04:30:34     321586
8               Delaware             US  2021-04-12 04:30:34      98570
9       Diamond Princess             US  2021-04-12 04:30:34         49
10  District of Columbia             US  2021-04-12 04:30:34      45830
11               Florida             US  2021-04-12 04:30:34    2124233
12               Georgia             US  2021-04-12 04:30:34    1073792
13        Grand Princess             US  2021-04-12 04:30:34        103
15                Hawaii             US  2021-04-12 04:30:34      32067
16                 Idaho             US  2021-04-12 04:30:34     183153
17              Illinois             US  2021-04-12 04:30:34    1279663
18               Indiana             US  2021-04-12 04:30:34     698692
19                  Iowa             US  2021-04-12 04:30:34     357019
20                Kansas             US  2021-04-12 04:30:34     305773
21              Kentucky             US  2021-04-12 04:30:34     433085
22             Louisiana             US  2021-04-12 04:30:34     448838
23                 Maine             US  2021-04-12 04:30:34      53960
24              Maryland             US  2021-04-12 04:30:34     426730
25         Massachusetts             US  2021-04-12 04:30:34     659569
26              Michigan             US  2021-04-12 04:30:34     820404
27             Minnesota             US  2021-04-12 04:30:34     542053
28           Mississippi             US  2021-04-12 04:30:34     307449
29              Missouri             US  2021-04-12 04:30:34     588626
30               Montana             US  2021-04-12 04:30:34     106183
31              Nebraska             US  2021-04-12 04:30:34     214207
32                Nevada             US  2021-04-12 04:30:34     308024
33         New Hampshire             US  2021-04-12 04:30:34      88854
34            New Jersey             US  2021-04-12 04:30:34     953490
35            New Mexico             US  2021-04-12 04:30:34     193368
36              New York             US  2021-04-12 04:30:34    1956594
37        North Carolina             US  2021-04-12 04:30:34     929406
38          North Dakota             US  2021-04-12 04:30:34     104745
40                  Ohio             US  2021-04-12 04:30:34    1039455
41              Oklahoma             US  2021-04-12 04:30:34     442805
42                Oregon             US  2021-04-12 04:30:34     170568
43          Pennsylvania             US  2021-04-12 04:30:34    1073924
45          Rhode Island             US  2021-04-12 04:30:34     141097
46        South Carolina             US  2021-04-12 04:30:34     562691
47          South Dakota             US  2021-04-12 04:30:34     119705
48             Tennessee             US  2021-04-12 04:30:34     822085
49                 Texas             US  2021-04-12 04:30:34    2826977
50                  Utah             US  2021-04-12 04:30:34     390104
51               Vermont             US  2021-04-12 04:30:34      21202
53              Virginia             US  2021-04-12 04:30:34     635552
54            Washington             US  2021-04-12 04:30:34     376230
55         West Virginia             US  2021-04-12 04:30:34     146169
56             Wisconsin             US  2021-04-12 04:30:34     645514
57               Wyoming             US  2021-04-12 04:30:34      56873

    Deaths
0    10712
1      313
3    17086
4     5661
5    60452
6     6157
7     7944
8     1578
9        0
10    1081
11   34021
12   19488
13       3
15     471
16    1993
17   23793
18   13148
19    5857
20    4933
21    6250
22   10216
23     750
24    8455
25   17387
26   17563
27    7035
28    7096
29    8885
30    1523
31    2220
32    5332
33    1257
34   24870
35    3976
36   51117
37   12248
38    1502
40   19200
41    6669
42    2440
43   25393
45    2638
46    9276
47    1946
48   12001
49   49212
50    2159
51     231
53   10472
54    5322
55    2745
56    7380
57     701

In [20]:
Covid19_Fact.to_csv('C:\\Users\\Logan\Covid19_Fact.csv', index = False)